\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<setup, include=FALSE>>=
knitr::opts_chunk$set(echo = TRUE)
@

\chapter{EUROEVOL_R and NeoNet apps}

\href{https://archaepigraph.shinyapps.io/EUROEVOL_R/}{EUROEVOL_R} is based on the EUROEVOL database covers the Central, Western and Northern Europe
\href{https://neolithic.shinyapps.io/NeoNet/}{NeoNet} is based on a Google Sheet and covers the Central Mediterranean



\end{document}